destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    false
markdown:    rdiscount
permalink: /:year/:month/:day/:title.html
url:         http://www.workingidea.com/
rdiscount:
  extensions: [smart]
